### ISSUE TITLE
Integration into the Text-to-video training repo

### ISSUE THREAD

**Issue by kabachuha** [srpkdyy/VideoLDM#1]
Hi, @srpkdyy! Thank you for your efforts!

Idk if you want to train it yourself, but will you mind integrating this model into the https://github.com/ExponentialML/Text-To-Video-Finetuning repo (which has training code, dataloaders and autocaptioners), so it will be more fast-forward for enthusiasts to start playing with it?

Or I'll just leave the code link here, so you won't have to duplicate the code 🙂

**Comment by srpkdyy** [comment]
Hi, @kabachuha!
Thank you for your comment!

Do you mean you want to use my model? Or are you advising that you already have an implementation?
If you want to use it, its no problem. Please note this model is not completed yet.
If you advised me, Thank you. But I love to implement some models even already released.

**Comment by kabachuha** [comment]
It's the former case. There is no open implementation of VideoLDM except for yours. I simply pointing to the infrastructure to *train* similar text2video models that could be useful to test train the model sooner and make sure the implementation works right.

Anyway, I thank you again and wish you good luck on this quest!
